---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
spec:
  selector:
    matchLabels:
      app: logger
  replicas: 1
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: # TODO fill me in
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: logger
spec:
  selector:
    app: logger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9376
